version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  back:
    image: back_keycloak:latest
    build: .
    container_name: back-keycloak-srv
    ports:
      - 9000:9000
    environment:
      DB_ADDR: mariadb
    network_mode: bridge