server:
  port: 9000

keycloak:
  auth-server-url: http://localhost:10001/auth
  ssl-required: none
  realm: test
  resource: test-api
  bearer-only: true
  credentials:
    secret: 98e37c89-fbe5-4961-a769-0e0024ad3d49

security:
  basic:
    enabled: false

spring:
  main:
    allow-bean-definition-overriding: true

#logging:
#  level:
#    web: DEBUG
#    root: DEBUG