version: '2.4'

services:
  mariadb:
    image: mariadb:10.5.2
    container_name: kvp-mariadb-srv
    restart: no
    volumes:
      - /opt/forge/mariadb/data:/var/lib/mysql
      - /opt/forge/mariadb/backup:/tmp/backup
      - /var/log/forge/mariadb:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    networks:
      - kvp_demo_keycloak
  keycloak:
    image: jboss/keycloak:9.0.2
    container_name: kvp-keycloak-srv
    restart: no
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "10000:8443"
      - "10001:8080"
    networks:
      - kvp_demo_keycloak

networks:
  kvp_demo_keycloak:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "193.100.10.0/24"

